name: CI/CD Nhac Automation

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  pull:
    name: Pulling from repo
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
  install_deps:
    runs-on: self-hosted
    name: Install deps
    needs: pull
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18.19.0
      - name: Install dependencies
        run: yarn install
      - name: Update prisma dependencies
        run: npx prisma generate
  run_tests:
    runs-on: self-hosted
    name: Run tests
    needs: install_deps
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18.19.0
      - name: Run tests
        run: yarn test
  build:
    runs-on: self-hosted
    name: Build
    needs: run_tests
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      VECTOR_INITIALIZER: ${{ secrets.VECTOR_INITIALIZER }}
      SECRET_KEY_ENCRYPT: ${{ secrets.SECRET_KEY_ENCRYPT }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18.19.0
      - name: Build
        run: yarn build
  upload_container:
    runs-on: self-hosted
    name: Update Container
    needs: build
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      VECTOR_INITIALIZER: ${{ secrets.VECTOR_INITIALIZER }}
      SECRET_KEY_ENCRYPT: ${{ secrets.SECRET_KEY_ENCRYPT }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - name: Stop container
        run: docker compose down -v || true
      - name: Delete image
        run: docker image rm nhac-dashboard --force || true
      - name: Container rebuild
        run: docker compose build --no-cache
      - name: Start container
        run: docker compose up -d --force-recreate --renew-anon-volumes
